baseURL: 'https://oplachko.com/'
languageCode: en-us
title: Nikolai Oplachko
theme: LoveIt

sectionPagesMenu: "main"

menu:
  main:
    - identifier: posts
      pre: ''
      post: ''
      name: Posts
      url: /posts/
      title: ''
      weight: 1
    - identifier: categories
      pre: ''
      post: ''
      name: Categories
      url: /categories/
      title: ''
      weight: 2
    - identifier: tags
      pre: ''
      post: ''
      name: Tags
      url: /tags/
      title: ''
      weight: 2



params:
  version: 0.2.X
  description: ''
  keywords:
    - Theme
    - Hugo
  defaultTheme: auto
  gitRepo: ''
  fingerprint: ''
  dateFormat: '2006-01-02'
  images:
    - /logo.png
  app:
    title: Nikolai Oplachko
    noFavicon: false
    svgFavicon: ''
    themeColor: '#ffffff'
    iconColor: '#5bbad5'
    tileColor: '#da532c'
  search:
    enable: true
    type: lunr
    contentLength: 4000
    placeholder: ''
    maxResultLength: 50
    snippetLength: 30
    highlightTag: em
    absoluteURL: false
    algolia:
      index: ''
      appID: ''
      searchKey: ''
  header:
    desktopMode: fixed
    mobileMode: auto
    title:
      logo: ''
      name: magnickolas' blog
      pre: ''
      post: ''
      typeit: false
  footer:
    enable: true
    custom: ''
    hugo: true
    copyright: true
    author: true
    since: 2020
    icp: ''
    license: ''
  section:
    paginate: 20
    dateFormat: 01-02
    rss: 10
  list:
    paginate: 20
    dateFormat: 01-02
    rss: 10
  home:
    rss: 10
    profile:
      enable: true
      gravatarEmail: ''
      avatarURL: /images/avatar.png
      title: ''
      subtitle: 'Hi, I''m Nikolai Oplachko (magnickolas)'
      typeit: false
      social: true
      disclaimer: ''
    posts:
      enable: true
      paginate: 10
  social:
    GitHub: magnickolas
    Linkedin: magnickolas
    Twitter: ''
    Instagram: ''
    Facebook: ''
    Telegram: magnickolas
    Medium: ''
    Gitlab: ''
    Youtubelegacy: ''
    Youtubecustom: ''
    Youtubechannel: ''
    Tumblr: ''
    Quora: ''
    Keybase: ''
    Pinterest: ''
    Reddit: ''
    Codepen: ''
    FreeCodeCamp: ''
    Bitbucket: ''
    Stackoverflow: ''
    Weibo: ''
    Odnoklassniki: ''
    VK: ''
    Flickr: ''
    Xing: ''
    Snapchat: ''
    Soundcloud: ''
    Spotify: ''
    Bandcamp: ''
    Paypal: ''
    Fivehundredpx: ''
    Mix: ''
    Goodreads: ''
    Lastfm: ''
    Foursquare: ''
    Hackernews: ''
    Kickstarter: ''
    Patreon: ''
    Steam: ''
    Twitch: ''
    Strava: ''
    Skype: ''
    Whatsapp: ''
    Zhihu: ''
    Douban: ''
    Angellist: ''
    Slidershare: ''
    Jsfiddle: ''
    Deviantart: ''
    Behance: ''
    Dribbble: ''
    Wordpress: ''
    Vine: ''
    Googlescholar: ''
    Researchgate: ''
    Mastodon: ''
    Thingiverse: ''
    Devto: ''
    Gitea: ''
    XMPP: ''
    Matrix: ''
    Bilibili: ''
    Email: magnickolas@pm.me
    RSS: true
  page:
    hiddenFromHomePage: false
    hiddenFromSearch: false
    twemoji: false
    lightgallery: false
    ruby: true
    fraction: true
    fontawesome: true
    linkToMarkdown: true
    rssFullText: false
    toc:
      enable: true
      auto: true
    math:
      enable: true
      blockLeftDelimiter: ''
      blockRightDelimiter: ''
      inlineLeftDelimiter: ''
      inlineRightDelimiter: ''
      copyTex: true
      mhchem: true
    code:
      copy: true
      maxShownLines: 50
    mapbox:
      accessToken: ''
      lightStyle: 'mapbox://styles/mapbox/light-v9'
      darkStyle: 'mapbox://styles/mapbox/dark-v9'
      navigation: true
      geolocate: true
      scale: true
      fullscreen: true
    share:
      enable: true
      Twitter: true
      Facebook: true
      Linkedin: false
      Whatsapp: true
      Pinterest: false
      Tumblr: false
      HackerNews: false
      Reddit: false
      VK: false
      Buffer: false
      Xing: false
      Line: true
      Instapaper: false
      Pocket: false
      Digg: false
      Stumbleupon: false
      Flipboard: false
      Weibo: true
      Renren: false
      Myspace: true
      Blogger: true
      Baidu: false
      Odnoklassniki: false
      Evernote: true
      Skype: false
      Trello: false
      Mix: false
    comment:
      enable: true
      schnack:
        enable: true
      disqus:
        enable: false
        shortname: 'biba'
      gitalk:
        enable: false
        owner: ''
        repo: ''
        clientId: ''
        clientSecret: ''
      valine:
        enable: false
        appId: ''
        appKey: ''
        placeholder: ''
        avatar: mp
        meta: ''
        pageSize: 10
        lang: ''
        visitor: true
        recordIP: true
        highlight: true
        enableQQ: false
        serverURLs: ''
        emoji: ''
      facebook:
        enable: false
        width: 100%
        numPosts: 10
        appId: ''
        languageCode: ''
      telegram:
        enable: false
        siteID: ''
        limit: 5
        height: ''
        color: ''
        colorful: true
        dislikes: false
        outlined: false
      commento:
        enable: false
      utterances:
        enable: false
        repo: ''
        issueTerm: pathname
        label: ''
        lightTheme: github-light
        darkTheme: github-dark
    library:
      css: {}
      js: {}
    seo:
      publisher:
        name: xxxx
        logo:
          url: logo.png
          width: 127
          height: 40
      logo:
        url: logo.png
        width: 127
        height: 40
      image:
        url: cover.png
        width: 800
        height: 600
  typeit:
    speed: 100
    cursorSpeed: 1000
    cursorChar: '|'
    duration: -1
  verification:
    google: ''
    bing: ''
    yandex: ''
    pinterest: ''
    baidu: ''
  analytics:
    enable: false
    google:
      id: ''
      anonymizeIP: true
    fathom:
      id: ''
      server: ''
  cookieconsent:
    enable: false
    content:
      message: ''
      dismiss: ''
      link: ''
  cdn:
    data: ''
  compatibility:
    polyfill: false
    objectFit: false
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
author:
  name: magnickolas
  email: magnickolas@pm.me
  link: ''
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
Permalinks:
  posts: ':year-:month/:title'
privacy:
  googleAnalytics: {}
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true
mediaTypes:
  text/plain:
    suffixes:
      - md
outputFormats:
  MarkDown:
    mediaType: text/plain
    isPlainText: true
    isHTML: false
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - MarkDown
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML

